### ISSUE TITLE
Plans to integrate with Neovim?

### ISSUE THREAD

**Issue by connorlay** [J3RN/tree-sitter-gleam#1]
Hello! I'm curious if there are any plans to integrate this grammar with Neovim via [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter). If not, I'm happy to help out with this 😄 Thanks!

**Comment by J3RN** [comment]
Hello @connorlay! Thanks for reaching out about this! While I don't have any plans surrounding neovim at the moment, I'd be delighted if you undertook the work to integrate `tree-sitter-gleam` into `nvim-treesitter`! I'm happy to answer questions that arise about the grammar either here in or in another issue as appropriate :smile:

**Comment by connorlay** [comment]
I started work on this today, you can follow my progress in this draft PR: https://github.com/nvim-treesitter/nvim-treesitter/pull/2462 😄

**Comment by wesleimp** [comment]
@connorlay Any updates for this issue? I've installed `gleam` support by running `TSInstall gleam` but it's not working

**Comment by connorlay** [comment]
@wesleimp You may need to add a filetype detection line, here is what I am using:
```
au BufRead,BufNewFile *.gleam set filetype=gleam
```

**Comment by connorlay** [comment]
Now that https://github.com/nvim-treesitter/nvim-treesitter/pull/2462 is merged, I think we can close this issue 😄
