### ISSUE TITLE
Add child nodes for the contents of a string?

### ISSUE THREAD

**Issue by connorlay** [J3RN/tree-sitter-gleam#12]
Howdy! As you know, I am working on integrating this grammar with neovim https://github.com/J3RN/tree-sitter-gleam/issues/1, during which I realized there is no node for string [escape sequences](https://gleam.run/book/tour/strings.html#escape-sequences). Without this node, I cannot highlight escape sequences similar to what I did with the nvim-treesitter Elixir [highlight queries](https://github.com/nvim-treesitter/nvim-treesitter/blob/a62971e0efcbe025693ccfaf688b62d185fd50da/queries/elixir/highlights.scm#L52).

For example, tree-sitter-elixir parses:
```elixir
"foo\nbar"
```
as the following tree of nodes:
```
(string
  quoted_start: """
  (quoted_content)
  (escape_sequence)
  (quoted_content)
  quoted_end: """)
```

I'm curious what you think!

**Comment by J3RN** [comment]
This is an interesting idea. We will, likely, eventually, have to do more string introspection seeing as [string interpolation is planned](https://github.com/gleam-lang/gleam/issues/1473), so this seems like a reasonable place to start. I'll probably not have time to look at this until the weekend, so you're welcome to give it a go if you'll have time sooner :grin:
